#cloud-config

write_files:
- path: /etc/systemd/system/nodered.service
  permissions: 0644
  owner: root
  content: |
    [Unit]
    Description=Node-red service
    After=gcr-online.target docker.socket docker-events-collector.service
    Wants=gcr-online.target docker.socket
    [Service]
    ExecStart=/usr/bin/docker run --rm --name=nodered -p 1880:1880 \
      ${image} \
    ExecStop=/usr/bin/docker stop nodered
runcmd:
- iptables -I INPUT 1 -p tcp -m tcp --dport 1880 -m state --state NEW,ESTABLISHED -j ACCEPT
- systemctl daemon-reload
- systemctl start nodered